Homework/1
csinn/CSharp-From-Zero-To-Hero-v2 pull request #19
Opened 2021-03-25 00:25 UTC by Laimonukas

Learning git. yay

2021-03-27 15:08 UTC, Almantask requested changes

2021-03-27 15:08 UTC, Almantask commented on Homework/1/CalcBMI.cs
> +        }
Split into smaller functions.

2021-03-27 15:08 UTC, Almantask commented on Homework/1/CalcBMI.cs
> +            }
all code is a blob, hard to read.

2021-03-28 04:39 UTC, Laimonukas commented on Homework/1/CalcBMI.cs
> +        }
Added age, weight and height functions.

2021-04-04 03:23 UTC, Almantask approved these changes

2021-04-04 03:23 UTC, Almantask commented
looks good

2021-04-04 03:23 UTC, closed without merging