Homework 5
csinn/CSharp-From-Zero-To-Hero-v2 pull request #56
Opened 2021-04-29 21:29 UTC by cjahermanns

2021-05-08 06:30 UTC, Almantask requested changes

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +            }
It works, but are those the requirements?

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +            if (_persons.TryGetValue(id, out var owner))
Move this to a separate line for better readability.
Validate first, meaning which if it's invalid- return not found and only then continue the rest of logic. That way, you eliminate the scope you don't need to care about fast, continuing with the essential "work as intended" behavior.

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +        [HttpPatch("{id:int}")]
You don't have to specify it's an it. I think it's a default based on the argument.

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +            if (id != value.Id) return BadRequest();
You should always specify a reason for a bad request.

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +                return NoContent();
NoContent refers that you were trying to get something and then there was nothing of that something. A successful deletion could say `Ok("Person with id X was deleted");` or just an `Ok();`

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +        public IActionResult GetPersons()
People not persons.

2021-05-08 06:30 UTC, Almantask commented on People.API/Controllers/PeopleController.cs
> +                {
This is not needed, because the other part will simply do nothing anyways if there are no pets of that person.

2021-05-08 06:30 UTC, Almantask commented on People.API/Models/Person.cs
> +        public int SpouseId { get; set; } = -1;
use a constant to specify the meaning of `-1`

2021-05-20 20:14 UTC, cjahermanns commented on People.API/Models/Person.cs
> +        public int SpouseId { get; set; } = -1;
Good idea! Never thought about using consts to declare special meanings xD

2021-05-20 20:29 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +            }
Nope... changed it to either `Created()` or `BadRequest()`. Is there a more appropriate result?

2021-05-20 20:32 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +        [HttpPatch("{id:int}")]
Ok, I removed the `int`s

2021-05-20 20:39 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +            if (id != value.Id) return BadRequest();
Did so in the add method, removed this one since I don't think it's necessary...

2021-05-20 20:42 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +        public IActionResult GetPersons()
You are right, Got distracted from all the `singular`s suggestions intellisense gives...

2021-05-20 20:46 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +                {
Ok, changed it to respond with either `Ok()` if the pet was removed, or `NotFound()` if there was no such pet.

2021-05-20 21:06 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +                return NoContent();
Got rid of it ^^

2021-05-20 21:14 UTC, cjahermanns commented on People.API/Controllers/PeopleController.cs
> +            if (_persons.TryGetValue(id, out var owner))
Well I now use a `FindPerson` method but is there a way to remove the duplicate `if (person == null) return NotFound()` stuff? I tried something like 
```cs
private IActionResult WorkWithPerson(int id, Action<Person> action)
{
  if (_people.TryGetValue(id, out var person))
  {
     action(person);
     return Ok(person);
  }
  return NotFound($"The person with id {id} could not be found.");
}
```
but I didn't like how limited I was with that approach...

2021-05-23 06:53 UTC, Almantask approved these changes
Looks good

2021-05-23 06:53 UTC, closed without merging